name = "destiny_inventory_tool"
description = "A Destiny inventory management tool for the desktop"
version = "0.21.0-dev"
licenses = "GPL-3.0-or-later"

authors = ["Andrew Athalye"]
maintainers = ["Andrew Athalye <andrewathalye@outlook.com>"]
maintainers-logins = ["andrewathalye"]

executables = ["inventory_tool"]

[[depends-on]]
gtkada = "*"
aws = "*"
vss = "^23.0.0"
gnatcoll = "^23.0.0"

[[pins]]
gtkada = { path = "alire_local/gtkada" }
aws = { path = "alire_local/aws" }

[build-switches]
"*".compile_checks = "Errors"
"*".style_checks = ["-gnatyaAbcdefhiIklnprtx-o"]
release.runtime_checks = "None"
validation.runtime_checks = "Everything"
development.optimization = "Performance"

[gpr-set-externals]
LIBRARY_TYPE = "relocatable"
