name = "destiny_inventory_tool"
description = "A Destiny inventory management tool for the desktop"
version = "0.13.0-dev"

authors = ["Andrew Athalye"]
maintainers = ["Andrew Athalye <andrewathalye@outlook.com>"]
maintainers-logins = ["andrewathalye"]

executables = ["inventory_tool"]
[[depends-on]]
gtkada = "^23.0.0"
aws = "^23.0.0"
vss = "^23.0.0"

[[pins]]
aws = { path = "alire_local/aws-23.0.0" }
gtkada = { path = "alire_local/gtkada-23.0.0" }

[build-switches]
"*".style_checks = ["-gnaty-3h"]
release.runtime_checks = "None"
development.optimization = "Performance"
