description = "Ada Web Server"
website = "https://github.com/adacore/aws"
name = "aws"
version = "23.0.0"
authors = ["AdaCore"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["aws.gpr"]
tags = ["aws", "web", "server", "http", "https", "soap", "wsdl", "ssl"]

# Since the AWS project doesn't build alone with just gprbuild we build and
# install with the Makefile from post-fetch action.
[[actions]]
type = "post-fetch"
command = ["make", "setup", "ZLIB=false", "DEMOS=false",
           "LAL=false", "XMLADA=false", "SOCKET=openssl", "prefix=install_dir",
           "PRJ_BUILD=Release"]

[[depends-on]]
gnatcoll = "~23.0.0"
make = "*"
gnat = ">=12"
openssl = "*"

[gpr-externals]
LIBRARY_TYPE = ["static", "relocatable"]
